name: format
on:
  pull_request:
  push:
    branches: main
jobs:
  formatter:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - uses: cachix/install-nix-action@v30
        with:
          nix_path: nixpkgs=channel:nixos-unstable

      - uses: cachix/cachix-action@v15
        with:
          name: "${{ secrets.CACHIX_CACHE_NAME }}"
          authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"

      - name: treefmt
        run: |
          nix run ./tools/nix#treefmt -- --fail-on-change --no-cache
