name: normal
on:
  pull_request:
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test-templates:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        language: [generic, python, go, rust]
    steps:
      - uses: actions/checkout@v4

      - uses: ./.github/actions/setup-nix
        with:
          cachix_cache_name: "${{ secrets.CACHIX_CACHE_NAME }}"
          cachix_auth_token: "${{ secrets.CACHIX_AUTH_TOKEN }}"

      - name: "Build & Test: ${{ matrix.language }}"
        run: just ci just maintenance::test ${{ matrix.language }}

  test-image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-nix
        with:
          cachix_cache_name: "${{ secrets.CACHIX_CACHE_NAME }}"
          cachix_auth_token: "${{ secrets.CACHIX_AUTH_TOKEN }}"
      - name: "Build & Test Images"
        run: just ci just maintenance::test-image
